CREATE TABLE IF NOT EXISTS  autor
(
    codau INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome  VARCHAR(40)                              NOT NULL,
    CONSTRAINT pk_autor PRIMARY KEY (codau)
);