CREATE TABLE IF NOT EXISTS assunto
(
    codas     INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    descricao VARCHAR(20)                              NOT NULL,
    CONSTRAINT pk_assunto PRIMARY KEY (codas)
);